os:
  - linux
services:
  - docker
language: node_js
node_js:
  - '10.15.3'
sudo: false
cache:
  directories:
    - node
    - node_modules
env:
  global:
    - NODE_VERSION=10.15.3
    - JHI_DISABLE_WEBPACK_LOGS=true
before_install:
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
  - nvm install $NODE_VERSION
  - npm install -g npm
  - node -v
  - npm -v
install:
  - npm install
notifications:
  webhooks:
    on_success: change # options: [always|never|change] default: always
    on_failure: always # options: [always|never|change] default: always
    on_start: false # default: false
